# Generated by Django 5.1.3 on 2026-01-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0002_promobanner_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='filter_values',
            field=models.ManyToManyField(blank=True, help_text='Selected filter values', related_name='order_items', to='products.filtervalue'),
        ),
    ]
