# Generated by Django 5.1.3 on 2026-01-31 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_filter_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sale',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
