# Generated by Django 5.1.3 on 2026-01-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_promobanner_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='image_mobile',
            field=models.ImageField(null=True, upload_to='banners-mobile/'),
        ),
    ]
