# Generated by Django 5.1.3 on 2026-01-28 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('value_ru', models.CharField(max_length=200)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filtertype')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.filtervalue'),
        ),
        migrations.CreateModel(
            name='ProductStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='products.product')),
            ],
        ),
    ]
