# Generated by Django 5.1.3 on 2026-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_promobanner_image_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code_public',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
