# Generated by Django 5.1.3 on 2026-01-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtertype',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
